name: Tests

on:
  pull_request:
    paths:
      - 'cmake/**'
      - 'src/**'
      - 'CMakeLists.txt'
  push:
    branches:
      - master
    paths:
      - 'cmake/**'
      - 'src/**'
      - 'CMakeLists.txt'

jobs:
  test_cxx:
    name: Test ${{ matrix.compiler }}, ${{ matrix.buildtype }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            compiler: gcc
          - os: ubuntu-latest
            compiler: clang
          - os: windows-latest
            compiler: msvc
        buildtype: [Debug, Release]
    env:
      BUILD_TYPE: ${{ matrix.buildtype }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up clang
        if: matrix.compiler == 'clang'
        uses: egor-tensin/setup-clang@v1
        with:
          platform: x64

      - name: Build
        run: |
          cmake -B build -DCOMMON_BUILD_TESTS=1 -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DCMKR_SKIP_GENERATION=ON
          cmake --build build --config ${{ env.BUILD_TYPE }} --parallel

      - name: Test (Unix)
        if: matrix.os == 'ubuntu-latest'
        run: ./build/common-tests

      - name: Test (Windows)
        if: matrix.os == 'windows-latest'
        run: .\build\${{ env.BUILD_TYPE }}\common-tests.exe
